### ISSUE TITLE
Urban Runner on PS Vita has everything Red

### ISSUE THREAD

**Issue by SasakiSadako** [rsn8887/scummvm#2]
![20180411_090907](https://user-images.githubusercontent.com/19212768/38601529-32103e18-3d68-11e8-948f-c2da4b52ab74.jpg)
On Scummvm on my PC everything is fine, but on my PS VIta only the grey frame has the original Color.
The ingame Graphics runs smooth, but have the wrong colors. Everything is in a hot red.

Tesded with Version 2.1.0.git-g37dbd365e

**Comment by rsn8887** [comment]
Confirmed bug on Vita. I currently don't know why this is happening. Thanks for reporting.

**Comment by rsn8887** [comment]
And on PSP, it is better, but blue where it should be red. Maybe some problem with the bit operations in YUV to RGB conversion in engines/gob/video_v6.cpp.

**Comment by rsn8887** [comment]
The commit by ccawley here
https://github.com/ccawley2011/scummvm/commit/85e9cf4077298443061e5783c1c0cc1c5f162998
fixes the issue on PSP.

Now I just have to check it on Vita.

**Comment by rsn8887** [comment]
Fixed with release 25
