### ISSUE TITLE
Simon the sorcerer 2, enable voice files crash

### ISSUE THREAD

**Issue by Nube79** [rsn8887/scummvm#3]
PS Vita

**Comment by Nube79** [comment]
works on scummvm_mod_1.13
crashes when enables the voices on 2.1 2.2

**Comment by rsn8887** [comment]
Hmm, I didn't change anything related to audio between those versions.

Which game version are you using? 

There's a windows version with `voices.wav`, and a dos version with `voices.voc`. 

One of them might work.

I will also try to test it myself this weekend if I find some time.

**Comment by Nube79** [comment]
simon2.gme
simon2.mp3

working on 1.13

is unsupported the mp3 format on the new version?

**Comment by rsn8887** [comment]
It might be that mp3 support broke at some point. I will test it, and if it is broken, make a new release that fixes it hopefully.

**Comment by rsn8887** [comment]
I confirm that mp3 is broken in release 25. I tested Simon2 with .ogg and .flac sound files and those work.

I will try to fix the mp3 playback asap.

**Comment by rsn8887** [comment]
mp3 is fixed in release 26

**Comment by Nube79** [comment]
thank you friend ! ❤❤❤

**Comment by Nube79** [comment]
works perfect now with mp3, thank you again  
**😍**
