### ISSUE TITLE
Vita nightly build installation error: 0x8010113D

### ISSUE THREAD

**Issue by Cardas26** [rsn8887/scummvm#4]
When I try to install the latest Vita Nightly (16-apr-2019) using the ScummVM buildbot and  VitaShell, the VPK installation fails with an error 0x8010113D. This might be related to the way PNG files in the VPK have been processed?

https://www.reddit.com/r/vitahacks/comments/56trqs/what_does_error_0x8010113d_mean/

The problem also exists when using the buildbot from the Vita Homebrew Browser application. Older versions from this Github site, like v28 (15-Jul-2018), install without a problem.

**Comment by rsn8887** [comment]
Thanks for notifying me! This is now fixed on official repo. The next, or second-next, nightly buildbot build should work again.

**Comment by Cardas26** [comment]
Yes, it's working great again from the buildbot releases. Thanks for the fast fix!
