### ISSUE TITLE
Include Vita Builds in Future Releases

### ISSUE THREAD

**Issue by 01y** [rsn8887/scummvm#5]
Written in the release text:

"release 29
stopped updating the Vita version here. The official buildbot development versions work just fine on Vita"

As of May 30, 2019, at least, this is no longer the case, with the nightly build crashing upon launch.

Having an older dev build posted here, which is confirmed to run, would be a nice convenience for users.

**Comment by rsn8887** [comment]
Thank you for notifying me of this problem.

I fixed this problem upstream.

The latest buildbot builds are not crashing anymore on Vita.

They are available here from the buildbot:
https://buildbot.scummvm.org/builds.html

Or here on VitaDB or via Vita Homebrew Browser:
http://vitadb.rinnegatamante.it/#/info/405

Regarding your request of making an older dev build available here: The older Vita dev build (release 28) is still available here if you go to the releases page and scroll down a while until you get to release 28.
