### ISSUE TITLE
Nightly build is crashing with c2-1282-1

### ISSUE THREAD

**Issue by SasakiSadako** [rsn8887/scummvm#6]
today i updated my scummvm on the vita to the lates nightly build, and after i tried to start it, i got an instant crash with the message c2-1282-1 and the location of the dmp file.
im not sure if you need the dmp file, but i add it in a zip file here.
thank so much for your great work for psvita software

[psp2core-1565572511-0x00019e2d0b-eboot.bin.psp2dmp.zip](https://github.com/rsn8887/scummvm/files/3490640/psp2core-1565572511-0x00019e2d0b-eboot.bin.psp2dmp.zip)

**Comment by rsn8887** [comment]
Thanks! I fixed it and the buildbot already made the fixed version. Just download latest nightly either from vitaDB, from vitaHBB, or from https://buildbot.scummvm.org/builds.html
