### ISSUE TITLE
Broken Sword 2.5 Videos extremely slow

### ISSUE THREAD

**Issue by SasakiSadako** [rsn8887/scummvm#7]
Today I tried to play the free broken Sword 2.5 with scummvm on my psvita. 
The Game runs fine, but the Videos like the intro, or the background animation in the main menu runs extremely slow. Maybe with just 1 FPS.
Of course the vita is not the most powerful device, but it's strange, that the game mostly runs fine, but the videos are unwatchable.

Beside that, it's neccecary to remove the shader option " like sharpen" and disable the scaler in the in game option from scummvm.

Thank you in advance

**Comment by rsn8887** [comment]
I only tested with original Broken Sword 1 and 2, never with 2.5. Maybe it uses a different format.

Try to use the latest nightly build: https://buildbot.scummvm.org/builds.html

Do you have “aspect ratio correction” tick mark on? If yes, try to turn it off. If you want correction, use the new “stretch mode”: “Fit to window (4:3)” instead.

Does the original broken sword intro still play fine for you?

**Comment by SasakiSadako** [comment]
Thank you for your comment. It seems the game use a different engine. Because scumm cannot load games directly from the main menu like the Originals.
The original games 1 and 2 runs great. The videos and in-game everything perfect.

I updated the scumm today, with the vite homebrew browser, I think it's already the newest version, or am I wrong?

I already turnt the aspect ratio off, but there was no change with the speed in the videos.

**Comment by rsn8887** [comment]
I suspect our humble Vita might just be too slow to decode those videos.

I just checked the ScummVM wiki for the sword 2.5 engine https://wiki.scummvm.org/index.php?title=Sword25
and it says:
```
Slow video playback, out of sync
```

**Comment by SasakiSadako** [comment]
So it seems to be a problem with the game actual with scummvm. I did not checked it on my notebook, just for seeing if it's run with all videos. But thank you for checking. I used Google, but mostly for looking problems about this game and the vita.
