### ISSUE TITLE
Problem with shaders (PS Vita)

### ISSUE THREAD

**Issue by Nube79** [rsn8887/scummvm#8]
Selecting 3x or Advmame3x, I get a orange screen lock, and need to delete the ini file to start scummvm again without problems.

**Comment by rsn8887** [comment]
That's not a shader, that's a software scaler. Shaders are on a different tab. 

But yeah any scaler higher than 2x is not supported. I am not sure why it crashes, it might just be some limit concerning max. surface size in Vita2d or something.

**Comment by Nube79** [comment]
It works in older versions.

**Comment by rsn8887** [comment]
Then I have no clue. Why would you use it btw? The Vita resolution is not high enough for 3x. 200 lines x 3 = 600 lines. Vita only has 544 lines. Or did you somehow manage to find a game in ScummVM that uses LESS than 200 display lines?

**Comment by Nube79** [comment]
Advmame3x looks much better, in version 28 works fine.

**Comment by Nube79** [comment]
![image](https://user-images.githubusercontent.com/38857477/68410480-143e5c80-0189-11ea-8be2-e94f7b1c36f4.png)

2x renders on lower resolution and is scaled to fit, 3x is rendered on higher resolution and better shaper, you can see the rounded window in the screenshot, are you right, 2x is not bad, but 3x is less blur and better algorithm.

PD: Screenshots taken with ScummVM v28 Vita.

![image](https://user-images.githubusercontent.com/38857477/68413291-469e8880-018e-11ea-84dd-e6b868855645.png)

**Comment by rsn8887** [comment]
How can you play with such ugly filters. Anyways I will try to look into it. A lot has changed in ScummVM recently, so it might not be a simple thing to fix. For example, Vita is now using more of the same graphics code as the other SDL-based platforms, less hacked stuff than I had before in v28.

**Comment by Nube79** [comment]
If you can fix it great, if you can't, remove the filters that don't work and fixed.
If you select them, the system will leak and cannot be accessed again unless you delete the ini or modify it.

**Comment by Nube79** [comment]
Never mind, works disabling aaa shader with the master version. Thanks.

**Comment by rsn8887** [comment]
Ok I will close this.
